# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: l3mode
    standard: EvmHypCollateral
    name: hackaToken
    symbol: hackaToken
    decimals: 18
    addressOrDenom: "0x6c17F57A1825293705DeB330b5a8d1FF4E248743"
    collateralAddressOrDenom: "0x697DAa49c4d93717cDdf6a9BE7e66421f3A26E66"
    connections:
      - token: ethereum|sepolia|0x5cbA335619c67b652D146bef6D68A4ca011344CF
  - chainName: sepolia
    standard: EvmHypSynthetic
    name: hackaToken
    symbol: hackaToken
    decimals: 18
    addressOrDenom: "0x5cbA335619c67b652D146bef6D68A4ca011344CF"
    connections:
      - token: ethereum|l3mode|0x6c17F57A1825293705DeB330b5a8d1FF4E248743
